### PR TITLE
Gameplay: Different colours are added.

### LINKED ISSUE #34: Gameplay: Add different color for different symbol
### Steps to reproduce
1. Compile and run with proper argument
2. Give suitable input

### Expected behavior
`X`, `O` and the borders will have different colors.

### Actual behavior
They have same color.

### Environment configuration
**Operating system**: Any

**Compiler**: Any

**Compiler version**: Any

### PR DESCRIPTION
**Pull request by satyamvats5**
Borders will be of blue colour.
'X' will be of red colour whereas
'O' will be of yellow colour.

fixes: #34

Signed-off-by: satyam kumar <satyamvats5@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Mentioned the issue number that it fixes
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Review by RudraNilBasu — APPROVED** [review]
Looks good :+1: 
One thing, will it be better to keep the spaces in the tcsetattr() function? I will leave that to @Progyan1997 to make the call.

Looks good overall, how about giving another colour once someone has won? (green colour maybe?)

**Comment by satyamvats5** [comment]
Okkk I will add some other colour when x or O wins and other colour when match is Tie!

**Comment by 0xTheProDev** [comment]
@satyamvats5 Avoid all the ANSI color code you have used. Visit `color.h` to get the MACRO names for respective colors. Furthermore try following our **Coding Style** to the best extent. And specify why we need `ctype.h` to be included.

**Comment by satyamvats5** [comment]
It means that I need to submit it using MACROS.? 
 ctype!!!!! I was trying to do something using it, but forgot to delete it😭

**Pull request closed without merging**
