### PR TITLE
shortlog : init

### LINKED ISSUE #4: helper.c: Initialize the board before game starts
Complete the implementation of _**void init()**_ which initialize the board before the game actually starts.

**Difficulty: Easy**

### PR DESCRIPTION
**Pull request by srj0224**
helper.c : initialisation of the board before the game actually starts
fixes    : #4
signed-off by: srj0224 <rajsuraj78@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Mentioned the issue number that it fixes
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by 0xTheProDev** [comment]
**Shortlog**: means one word describe your commit.
**Commit Title**: The operation that is performed by the commit.

**Comment by RudraNilBasu** [comment]
One more thing about the commit message:
 In the Signed-off-by: name <email>, provide your full name,
not the username
 Refer this as an example:
https://github.com/BytesClub/Xplode/commits/master

- *Rudra Nil Basu*

**Comment by srj0224** [comment]
okay bhaiya @Progyan1997  @RudraNilBasu 
from next time i'll keep an eye on it.
i will try my best not to repeat these mistakes again.

**Comment by 0xTheProDev** [comment]
@srj0224 
This issue was to set initial data to the array, not to print it.
The **`show`** function is already taking care of this part.

**Pull request closed without merging**
